- packages/agent-js/README.md
- packages/agent-js/src/process.js
- packages/agent-js/test/httpServer.js
- packages/agent-js/test/process.js
Fixes #5 
Typo in README has been fixed.
> agent-js: fix "DISABLED" evidence sent to tmstore

- packages/agent-ui/src/test/app.test.js
- packages/agent-ui/src/test/components/agentInfoPage.test.js
- packages/agent-ui/src/test/components/app.test.js
This is just a small project structure refactoring
> agent-ui: split tests in dedicated folders

- packages/agent-client-js/.gitignore
- packages/agent-client-js/.npmignore
- packages/agent-client-js/package.json
- packages/agent-js/.gitignore
- packages/agent-js/.npmignore
- packages/agent-js/package.json
From isparta, for code coverage
> agent-js, agent-client-js: switch to nyc

- packages/react-mapexplorer/example/package-lock.json
- packages/react-mapexplorer/example/package.json
- packages/react-mapexplorer/example/react-mapexplorer.js
- packages/react-mapexplorer/package-lock.json
- packages/react-mapexplorer/package.json
- packages/react-mapexplorer/src/BitcoinEvidence.js
- packages/react-mapexplorer/src/DummyEvidence.js
- packages/react-mapexplorer/src/MapExplorer.js
- packages/react-mapexplorer/src/MerklePathComponent.js
Fixes issues between Radium and PropTypes
> react-mapexplorer: fix dependencies

- .eslintrc.json
- .gitignore
- packages/agent-ui/src/components/processInfoPage.js
- packages/agent-ui/src/setupTests.js
- packages/agent-ui/src/test/builders/index.js
- packages/agent-ui/src/test/builders/testProcessBuilder.js
- packages/agent-ui/src/test/builders/testStateBuilder.js
- packages/agent-ui/src/test/components/processInfoPage.test.js
Add more unit tests for the process section component
Add data builders for test objects
> agent-ui: add more unit tests

- packages/agent-client-js/README.md
- packages/agent-client-js/src/fromSegment.js
- packages/agent-client-js/src/getAgent.js
- packages/agent-client-js/src/getProcess.js
- packages/agent-client-js/test/getProcess.js
> agent-client-js: add promise getProcess function

- packages/agent-ui/src/components/agentInfoPage.js
- packages/agent-ui/src/components/leftDrawer.js
- packages/agent-ui/src/components/processInfoPage.js
- packages/agent-ui/src/components/topBar.js
- packages/agent-ui/src/style/app.js
- packages/agent-ui/src/test/components/processInfoPage.test.js
I really think I'm doing it wrong so I'm creating this PR to gather some feedback from experts :).
In my opinion we shouldn't have to specify explicit width / margins and components should flow and align themselves correctly (but it's not the case yet).
@clinejm jérémie told me you have experience with React / Material UI, do you know how we're supposed to style our components correctly?
> agent-ui: material-ui and align components 

- packages/agent-ui/src/actions/getAgent.js
- packages/agent-ui/src/actions/getAgent.test.js
- packages/agent-ui/src/containers/leftNavigation.js
- packages/agent-ui/src/containers/leftNavigation.test.js
- packages/agent-ui/src/reducers/agents.js
- packages/agent-ui/src/reducers/agents.test.js
- packages/agent-ui/src/test/builders/index.js
- packages/agent-ui/src/test/builders/testAgentBuilder.js
- packages/agent-ui/src/test/builders/testProcessBuilder.js
Implement reducers for getting agent info.
List navigation links to available agents and processes in the left menu.
> agent-ui: load agent information

- packages/agent-ui/src/containers/agentsPage.test.js
Luckily we don't have that many tests that can be updated to shallow rendering :)
> agent-ui: agents page can use shallow rendering in unit tests

- packages/agent-ui/src/actions/getSegments.js
- packages/agent-ui/src/actions/getSegments.test.js
- packages/agent-ui/src/containers/processSegmentsPage.js
- packages/agent-ui/src/containers/processSegmentsPage.test.js
- packages/agent-ui/src/reducers/maps.js
- packages/agent-ui/src/reducers/maps.test.js
- packages/agent-ui/src/reducers/segments.js
- packages/agent-ui/src/reducers/segments.test.js
very similar to https://github.com/stratumn/indigo-js/pull/77 for process segments page
> agent-ui: add process segments page

- packages/agent-ui/package.json
- packages/agent-ui/src/containers/index.js
- packages/agent-ui/src/containers/root.js
- packages/agent-ui/src/index.js
- packages/agent-ui/src/store/configure.js
- packages/agent-ui/yarn.lock
https://github.com/stratumn/indigo-js/issues/74
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/82)
> agent-ui: use redux-persist

- packages/agent-client-js/src/httpAdaptor.js
- packages/agent-client-js/src/objectAdaptor.js
- packages/agent-client-js/src/processify.js
- packages/agent-client-js/src/segmentify.js
- packages/agent-client-js/src/withRefs.js
- packages/agent-client-js/test/createMap.js
- packages/agent-client-js/test/withRefs.js
- packages/agent-client-js/yarn.lock
`(process|segment).withRefs(references)` adds a `refs` field containing the list `references`, which are then passed to the agent through the adaptor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/84)
> agent-client-js: add withRefs interface

- packages/agent-ui/src/containers/processMapsPage.js
- packages/agent-ui/src/containers/processMapsPage.test.js
add navlinks on the maps page to point to the mapexplorer page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/97)
> agent-ui: add navlinks to map explorer page

- packages/agent-ui/package.json
- packages/agent-ui/src/actions/createMap.js
- packages/agent-ui/src/containers/agentInfoPage.test.js
- packages/agent-ui/src/containers/agentsPage.test.js
- packages/agent-ui/src/containers/createMapDialog.test.js
- packages/agent-ui/src/containers/mapPage.test.js
- packages/agent-ui/src/containers/processInfoPage.js
- packages/agent-ui/src/containers/processInfoPage.test.js
- packages/agent-ui/yarn.lock
upgrading to react-scripts 1.0.15 helped with the polyfill warning. I also cleaned up a bunch of test warnings (missing required props)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/100)
> agent-ui: cleanup test warnings

- packages/agent-ui/src/containers/app.js
- packages/agent-ui/src/containers/leftNavigation.js
- packages/agent-ui/src/containers/processMapsPage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/107)
> agent-ui: remove console logs

- packages/agent-ui/src/containers/segmentPage.js
- packages/agent-ui/src/containers/segmentPage.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/117)
> agent-ui: use pre html tag to format segment json correcly

- packages/agent-ui/src/containers/leftNavigation.js
- packages/agent-ui/src/containers/leftNavigation.test.js
conditionally format the left nav menu based on location to only display the children of the relevant path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/118)
> agent-ui: left navigation formatting

- packages/agent-ui/src/actions/createMap.js
- packages/agent-ui/src/actions/createMap.test.js
- packages/agent-ui/src/containers/createMapDialog.js
- packages/agent-ui/src/containers/createMapDialog.test.js
- packages/agent-ui/src/reducers/createMap.js
- packages/agent-ui/src/reducers/createMap.test.js
Fixing the assumption that the "init" method of a process takes a single argument.
It can have multiple arguments that we need to provide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/122)
> agent-ui: create map with args

- packages/agent-client-js/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/125)
> agent-client-js: update FindSegments documentation on README

- packages/agent-ui/src/actions/appendSegment.js
- packages/agent-ui/src/actions/appendSegment.test.js
- packages/agent-ui/src/containers/appendSegmentDialog.js
- packages/agent-ui/src/containers/appendSegmentDialog.test.js
- packages/agent-ui/src/containers/contentPage.test.js
- packages/agent-ui/src/containers/mapPage.js
- packages/agent-ui/src/containers/mapPage.test.js
- packages/agent-ui/src/reducers/appendSegment.js
- packages/agent-ui/src/reducers/appendSegment.test.js
- packages/agent-ui/src/test/builders/state/testStateBuilder.js
Finish the append segment feature.
Now the dialog allows you to select which action to use, provide the arguments and create the segment.
It then correctly refreshes the map explorer view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/126)
> agent-ui: append segment dialog

- packages/agent-client-js/test/findSegments.js
- packages/agent-js/src/create.js
- packages/agent-js/src/memoryStore.js
- packages/agent-js/src/process.js
- packages/agent-js/src/storeHttpClient.js
- packages/agent-js/test/memoryStore.js
- packages/agent-js/test/storeHttpClient.js
The tests in the client were also updated to test the linkHashes
options in the findSegments method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/129)
> agent-js: add linkHashes options to findSegments

- packages/agent-js/README.md
- packages/agent-js/doc/swagger.json
- packages/agent-js/doc/swagger2markup.properties
- packages/agent-js/doc/swaggerDef.js
- packages/agent-js/doc/swaggerDoc.md
- packages/agent-js/package.json
- packages/agent-js/src/httpServer.js
- packages/agent-js/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/131)
> agent-js: document HTTP API using OpenAPI 2.0

- packages/agent-ui/src/components/index.js
- packages/agent-ui/src/components/mapsList.js
- packages/agent-ui/src/components/mapsList.test.js
- packages/agent-ui/src/components/segmentsFilter.js
- packages/agent-ui/src/components/segmentsFilter.test.js
- packages/agent-ui/src/components/segmentsList.js
- packages/agent-ui/src/containers/processMapsPage.js
- packages/agent-ui/src/containers/processMapsPage.test.js
- packages/agent-ui/src/styles/tables.js
Add some styling to the maps and segments pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/136)
> agent-ui: maps and segments pages are pretty

- packages/agent-ui/src/components/agentsManager.js
- packages/agent-ui/src/components/agentsManager.test.js
- packages/agent-ui/src/components/index.js
- packages/agent-ui/src/components/prettyDivider.js
- packages/agent-ui/src/containers/agentInfoPage.js
- packages/agent-ui/src/containers/agentInfoPage.test.js
- packages/agent-ui/src/containers/agentsPage.js
- packages/agent-ui/src/containers/agentsPage.test.js
- packages/agent-ui/src/containers/processInfoPage.js
- packages/agent-ui/src/containers/segmentPage.js
- packages/agent-ui/src/containers/segmentPage.test.js
Add styling to the agent, process, segment and add agent pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/137)
> agent-ui: style agent and process pages

- packages/agent-js/Dockerfile.development
- packages/agent-js/Dockerfile.development.alpine
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/139)
> agent-js: use Node 8 in Docker images

- packages/agent-client-js/src/httpAdaptor.js
- packages/agent-client-js/src/objectAdaptor.js
- packages/agent-client-js/src/processify.js
- packages/agent-client-js/src/segmentify.js
- packages/agent-client-js/src/withRefs.js
- packages/agent-client-js/test/createMap.js
- packages/agent-client-js/test/withRefs.js
- packages/agent-client-js/yarn.lock
- packages/agent-js/src/memoryStore.js
- packages/agent-js/src/process.js
- packages/agent-js/src/processify.js
- packages/agent-js/test/create.js
- packages/agent-js/test/getActionsInfo.js
- packages/agent-js/test/httpServer.js
- packages/agent-js/test/plugins/index.js
- packages/agent-js/test/process.js
- packages/agent-js/test/utils/basicActions.js
- packages/agent-js/test/utils/refs.js
Resolves #12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/65)
> agent-js: add new refs argument to createMap and createSegment

- packages/agent-client-js/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/140)
> agent-client-js: update doc with withRefs API

- packages/agent-ui/src/components/mapsList.js
- packages/agent-ui/src/components/mapsList.test.js
- packages/agent-ui/src/components/segmentsList.js
- packages/agent-ui/src/components/segmentsList.test.js
Change the display message when no segments or maps are found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/144)
> agent-ui: change display when no maps or segments found

- packages/agent-js/src/memoryStore.js
- packages/agent-js/test/memoryStore.js
To be consistent with https://github.com/stratumn/sdk/blob/master/store/store.go#L23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/151)
> agent-js: default and max limit for memoryStore (#90)

- packages/agent-client-js/yarn.lock
- packages/agent-js/package.json
- packages/agent-js/yarn.lock
- packages/cs-validator/package.json
- packages/cs-validator/rollupPlugins.js
- packages/cs-validator/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/154)
> *: bump canonicaljson to stable version

- packages/agent-client-js/src/httpAdaptor.js
- packages/agent-client-js/test/getAgent.js
Fix #142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/155)
> agent-client-js: safely concatenate agent url

- packages/agent-ui/src/actions/appendSegment.js
- packages/agent-ui/src/actions/appendSegment.test.js
- packages/agent-ui/src/actions/selectSegment.js
- packages/agent-ui/src/actions/selectSegment.test.js
- packages/agent-ui/src/components/segmentsFilter.js
- packages/agent-ui/src/components/segmentsFilter.test.js
- packages/agent-ui/src/containers/selectRefsDialog.js
- packages/agent-ui/src/containers/selectRefsDialog.test.js
- packages/agent-ui/src/containers/topBar.js
- packages/agent-ui/src/reducers/mapExplorer.js
- packages/agent-ui/src/reducers/mapExplorer.test.js
- packages/agent-ui/src/test/builders/state/testStateBuilder.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/158)
> agent-ui: reference other process in segment

- packages/angular-mapexplorer/README.md
- packages/angular-mapexplorer/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/160)
> angular-mapexplorer: update description

- packages/react-mapexplorer/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/159)
> react-mapexplorer: fix repository url

- packages/agent-ui/src/utils/webSocketHelpers.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/172)
> agent-ui: fix mock websocket async

- packages/angular-mapexplorer/docs/styles/segment.css
- packages/angular-mapexplorer/src/stTmpopEvidence.directive.js
- packages/angular-mapexplorer/test/fixtures/chainscript.json
- packages/angular-mapexplorer/views/bitcoinevidence.html
- packages/angular-mapexplorer/views/evidences.html
- packages/angular-mapexplorer/views/tmpopevidence.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/177)
> angular-mapexplorer: update evidences directives  with new format

- packages/agent-ui/package.json
- packages/agent-ui/src/components/agentsManager.js
- packages/agent-ui/src/components/agentsManager.test.js
- packages/agent-ui/src/containers/agentsPage.js
- packages/agent-ui/src/containers/agentsPage.test.js
- packages/agent-ui/src/styles/tables.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/181)
> agent-ui: display failed agents in red

- .travis.yml
- package.json
- packages/agent-client-js/package.json
- packages/agent-js/package.json
- packages/angular-mapexplorer/karma.conf.js
- packages/angular-mapexplorer/package.json
- packages/cs-validator/karma.conf.js
- packages/cs-validator/package.json
- packages/mapexplorer-core/karma.conf.js
- packages/mapexplorer-core/package.json
- packages/react-mapexplorer/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/184)
> *: use yarn explicitly and run tests in parallel

- .eslintrc.json
- packages/agent-ui/src/utils/webSocketHelpers.js
- packages/agent-ui/src/utils/webSocketHelpers.test.js
I've run the tests on travis at least 4 times and it has not failed yet. So I hope it will not fail anymore... We'll see!
My fix was inspired by: https://github.com/thoov/mock-socket/issues/176 that looked really relevant to us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/191)
> agent-ui: try and fix random websocket test

- packages/cs-validator/package.json
we don't build a minified version of the library
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/193)
> cs-validator: fix postpublish script

- packages/agent-client-js/package.json
- packages/agent-js/package.json
- packages/agent-sample/package.json
- packages/agent-sample/yarn.lock
- packages/agent-ui/package.json
- packages/angular-mapexplorer/package.json
- packages/angular2-mapexplorer/package.json
- packages/cs-validator/package.json
- packages/mapexplorer-core/package.json
- packages/react-mapexplorer/package.json
- packages/tmpop-explorer/app/package.json
- packages/tmpop-explorer/package.json
Releasing 0.2.0-0 version for testing before the official 0.2.0 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/192)
> release: 0.2.0-0

- packages/agent-client-js/package.json
- packages/agent-js/package.json
- packages/agent-sample/package.json
- packages/agent-ui/package.json
- packages/angular-mapexplorer/package.json
- packages/angular2-mapexplorer/package.json
- packages/cs-validator/package.json
- packages/mapexplorer-core/package.json
- packages/react-mapexplorer/package.json
- packages/tmpop-explorer/app/package.json
- packages/tmpop-explorer/package.json
This confirms that the sed fix works properly 
- @indigoframework/client@0.2.0-1
- @indigoframework/agent@0.2.0-1
- @indigoframework/agent-sample@0.2.0-1
- @indigoframework/agent-ui@0.2.0-1
- @indigoframework/angular-mapexplorer@0.2.0-1
- @indigoframework/angular2-mapexplorer@0.2.0-1
- @indigoframework/cs-validator@0.2.0-1
- @indigoframework/mapexplorer-core@0.2.0-1
- @indigoframework/react-mapexplorer@0.2.0-1
- @indigoframework/tmpop-explorer@0.2.0-1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/194)
> publish 0.2.0-1

- README.md
- packages/agent-client-js/README.md
- packages/agent-js/README.md
- packages/angular-mapexplorer/README.md
- packages/angular2-mapexplorer/README.md
- packages/cs-validator/README.md
- packages/mapexplorer-core/README.md
- packages/react-mapexplorer/README.md
- packages/tmpop-explorer/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/195)
> *: update npm badges

- packages/agent-sample/Dockerfile
- packages/agent-sample/index.js
- packages/agent-sample/package.json
- packages/agent-sample/test/actions-message.js
- packages/agent-sample/test/actions-warehouse.js
- packages/agent-sample/yarn.lock
I forgot to update agent-sample to the new @indigoframework npm package.
The docker image was also wrong, resulting in issues at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/197)
> agent-sample: update docker file and agent reference

- packages/tmpop-explorer/package.json
- packages/tmpop-explorer/rollup.config.js
- packages/tmpop-explorer/src/TMReader.js
- packages/tmpop-explorer/yarn.lock
- Work around https://github.com/rollup/rollup-plugin-commonjs/issues/247
- Stop using bluebird for promises
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/199)
> tmpop-explorer: fix rollup configuration

- packages/react-mapexplorer/src/mapExplorerCss.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/205)
> react-mapexplorer: fix close button style

- packages/tmpop-explorer/src/components/SearchInput.js
Fixes #208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/210)
> tmpop-explorer: fix search input

- packages/agent-ui/src/containers/selectRefsDialog.js
I think this fixes https://github.com/stratumn/indigo-js/issues/207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/211)
> agent-ui: fix selectRefsDialog

- packages/agent-ui/src/containers/processInfoPage.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/220)
> agent-ui: split fossilizers visually on process page

- packages/angular-mapexplorer/src/stBitcoinEvidence.directive.js
- packages/angular-mapexplorer/views/bitcoinevidence.html
- packages/angular2-mapexplorer/src/chain-tree-builder.service.ts
- packages/angular2-mapexplorer/src/map-validator.service.ts
- packages/angular2-mapexplorer/src/st-bitcoin-evidence/st-bitcoin-evidence.component.html
- packages/angular2-mapexplorer/src/st-bitcoin-evidence/st-bitcoin-evidence.component.ts
- packages/angular2-mapexplorer/src/st-dummy-evidence/st-dummy-evidence.component.ts
- packages/angular2-mapexplorer/src/st-evidences/st-evidences.component.ts
- packages/angular2-mapexplorer/src/st-map-explorer/st-map-explorer.component.ts
- packages/angular2-mapexplorer/src/st-merkle-path-tree/st-merkle-path-tree.component.ts
- packages/react-mapexplorer/src/BitcoinEvidence.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/221)
> Handle bitcoin testnet transactions

- packages/react-mapexplorer/src/mapExplorerCss.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/222)
> react-mapexplorer: improve style

- packages/agent-sample/Dockerfile.local
- packages/agent-sample/README.md
- packages/agent-sample/index.js
- packages/agent-ui/Dockerfile.local
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/223)
> agent-sample: support single fossilizer

- packages/agent-client-js/package.json
- packages/agent-js/package.json
- packages/agent-sample/package.json
- packages/agent-ui/package.json
- packages/angular-mapexplorer/package.json
- packages/angular2-mapexplorer/package.json
- packages/cs-validator/package.json
- packages/mapexplorer-core/package.json
- packages/react-mapexplorer/package.json
- packages/tmpop-explorer/app/package.json
- packages/tmpop-explorer/package.json
- @indigoframework/client@0.2.0
- @indigoframework/agent@0.2.0
- @indigoframework/agent-sample@0.2.0
- @indigoframework/agent-ui@0.2.0
- @indigoframework/angular-mapexplorer@0.2.0
- @indigoframework/angular2-mapexplorer@0.2.0
- @indigoframework/cs-validator@0.2.0
- @indigoframework/mapexplorer-core@0.2.0
- @indigoframework/react-mapexplorer@0.2.0
- @indigoframework/tmpop-explorer@0.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/224)
> Publish 0.2.0

- README.md
- packages/agent-client-js/README.md
- packages/agent-js/README.md
- packages/angular-mapexplorer/README.md
- packages/cs-validator/README.md
- packages/mapexplorer-core/README.md
- packages/react-mapexplorer/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/227)
> Cleanup README files

- packages/mapexplorer-core/src/ChainTree.js
- packages/mapexplorer-core/src/ChainTreeBuilder.js
- packages/mapexplorer-core/test/integration/ChainTree.test.js
Add an option to not focus on segment on click
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/233)
> add option to not focus on segment

- README.md
- packages/agent-client-js/package.json
- packages/agent-client-js/src/makeQueryString.js
- packages/agent-js/package.json
- packages/agent-js/src/makeQueryString.js
- packages/agent-sample/README.md
- packages/agent-sample/package.json
- packages/agent-ui/package.json
- packages/agent-ui/src/containers/agentInfoPage.js
- packages/agent-ui/src/containers/leftNavigation.js
- packages/angular-mapexplorer/README.md
- packages/angular-mapexplorer/package.json
- packages/cs-validator/package.json
- packages/mapexplorer-core/package.json
- packages/react-mapexplorer/package.json
- packages/tmpop-explorer/app/public/index.html
- packages/tmpop-explorer/package.json
- packages/utils/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/237)
> *: rename repository to js-indigocore

- packages/cs-validator/karma.conf.js
- packages/cs-validator/package.json
- packages/cs-validator/rollupPlugins.js
- packages/cs-validator/src/MapValidator.js
- packages/cs-validator/src/SegmentValidator.js
- packages/cs-validator/test/fixtures/signatures/sigBadFormat.json
- packages/cs-validator/test/fixtures/signatures/sigBadPublicKeyLength.json
- packages/cs-validator/test/fixtures/signatures/sigBadScheme.json
- packages/cs-validator/test/fixtures/signatures/sigBadSigLength.json
- packages/cs-validator/test/fixtures/signatures/sigEmptyPayload.json
- packages/cs-validator/test/fixtures/signatures/sigNoMatch.json
- packages/cs-validator/test/fixtures/validSegment.json
- packages/cs-validator/test/integration/SegmentValidator.test.js
- packages/cs-validator/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/239)
> cs-validator: verify ed25519 signatures

- packages/tmpop-explorer/src/components/Status.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/241)
> Upgrade tmpop explorer

- packages/angular-mapexplorer/karma.conf.js
- packages/angular-mapexplorer/package.json
- packages/angular2-mapexplorer/karma.conf.js
- packages/angular2-mapexplorer/package.json
- packages/cs-validator/karma.conf.js
- packages/mapexplorer-core/karma.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/246)
> *: update karma conf for semaphoreCI

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/248)
> doc: switch travis badge with semaphoreci

- packages/agent-client-js/src/sign.js
- packages/agent-client-js/test/createMap.js
- packages/agent-client-js/test/sign.js
- packages/agent-js/Dockerfile.local
- packages/agent-js/src/handleResponse.js
- packages/agent-ui/src/actions/appendSegment.js
- packages/agent-ui/src/actions/appendSegment.test.js
- packages/agent-ui/src/containers/appendSegmentDialog.js
- packages/agent-ui/src/containers/selectRefsDialog.js
- packages/agent-ui/src/containers/selectRefsDialog.test.js
- packages/agent-ui/src/containers/signedAttributes.js
- packages/agent-ui/src/reducers/signedAttributes.js
- packages/agent-ui/src/reducers/signedAttributes.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/250)
> agent-ui, agent-client-js: fix signatures issues

- packages/agent-client-js/package.json
- packages/agent-client-js/src/segmentify.js
- packages/agent-client-js/test/segmentify.js
- packages/agent-client-js/test/utils/agentHttpServer.js
- packages/agent-client-js/yarn.lock
- packages/agent-js/package.json
- packages/agent-js/src/handleResponse.js
- packages/agent-js/yarn.lock
- packages/agent-ui/src/containers/signedAttributes.js
- packages/cs-validator/package.json
- packages/cs-validator/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/251)
> agent, client, ui: error handling fixes

- packages/agent-ui/src/components/keyManager.js
- packages/agent-ui/src/components/segmentsList.js
- packages/agent-ui/src/containers/selectRefsDialog.js
- packages/agent-ui/src/containers/selectRefsDialog.test.js
- packages/agent-ui/src/test/builders/state/testStateBuilder.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/256)
>  agent-ui: remove already selected segments (refs)

- packages/ember-mapexplorer/addon/components/tmpop-evidence.js
- packages/ember-mapexplorer/addon/templates/components/tmpop-evidence.hbs
- packages/ember-mapexplorer/package.json
- packages/ember-mapexplorer/tests/dummy/app/controllers/application.js
- packages/ember-mapexplorer/tests/integration/components/tmpop-evidence-test.js
- packages/ember-mapexplorer/yarn.lock
- packages/mapexplorer-core/assets/stylesheets/map.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/259)
> ember-mapexplorer: more data in TM Evidence

- packages/agent-ui/src/actions/appendSegment.js
- packages/agent-ui/src/actions/appendSegment.test.js
- packages/agent-ui/src/actions/createMap.js
- packages/agent-ui/src/actions/createMap.test.js
- packages/agent-ui/src/actions/uploadKey.js
- packages/agent-ui/src/components/keyManager.js
- packages/agent-ui/src/components/keyManager.test.js
- packages/agent-ui/src/containers/agentsPage.js
- packages/agent-ui/src/containers/appendSegmentDialog.js
- packages/agent-ui/src/containers/createMapDialog.js
- packages/agent-ui/src/containers/signedAttributes.js
- packages/agent-ui/src/reducers/uploadKey.test.js
- packages/agent-ui/src/styles/keyManager.js
- packages/agent-ui/src/test/builders/state/testKeyBuilder.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/261)
> agent-ui: handle PEM keys

- packages/agent-client-js/src/index.js
- packages/angular-mapexplorer/package.json
- packages/cs-validator/package.json
- packages/cs-validator/src/SegmentValidator.js
- packages/cs-validator/test/fixtures/signatures/sigBadFormat.json
- packages/cs-validator/test/fixtures/signatures/sigBadPublicKeyLength.json
- packages/cs-validator/test/fixtures/signatures/sigBadScheme.json
- packages/cs-validator/test/fixtures/signatures/sigBadSigLength.json
- packages/cs-validator/test/fixtures/signatures/sigEmptyPayload.json
- packages/cs-validator/test/fixtures/signatures/sigNoMatch.json
- packages/cs-validator/test/fixtures/validSegment.json
- packages/cs-validator/test/integration/SegmentValidator.test.js
- packages/cs-validator/yarn.lock
- packages/mapexplorer-core/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/263)
> cs-validator: verify PEM signatures

- packages/agent-client-js/src/encoding.js
- packages/agent-client-js/test/encoding.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/264)
> agent-client-js: fix PEM issues

- .vscode/launch.json
- README.md
- packages/agent-js/doc/swagger.json
- packages/agent-js/doc/swaggerDoc.md
- packages/ember-mapexplorer/package.json
- packages/react-mapexplorer/example/package.json
- packages/tmpop-explorer/app/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/266)
> *: bump doc & subpackages version

- packages/mapexplorer-core/src/ChainTree.js
- packages/mapexplorer-core/src/nodes.js
- packages/mapexplorer-core/test/fixtures/fullMapWithRefs.json
- packages/mapexplorer-core/test/integration/ChainTree.test.js
- packages/mapexplorer-core/test/unit/nodes.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/269)
> mapexplorer-core: load external ref at display

- packages/angular-mapexplorer/views/mapexplorer.html
- packages/angular2-mapexplorer/docs_src/styles.css
- packages/angular2-mapexplorer/src/st-map-explorer/st-map-explorer.component.css
- packages/angular2-mapexplorer/src/st-map-explorer/st-map-explorer.component.html
- packages/ember-mapexplorer/addon/styles/addon.scss
- packages/ember-mapexplorer/addon/templates/components/map-explorer.hbs
- packages/mapexplorer-core/src/MerklePathTree.js
- packages/react-mapexplorer/src/MapExplorer.js
- packages/react-mapexplorer/src/mapExplorerCss.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/271)
> *-mapexplorer: ui fixes

- packages/agent-ui/src/containers/topBar.js
Resolves #272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/273)
> agent-ui: fix segment link

- packages/agent-ui/package.json
- packages/agent-ui/src/components/segmentsFilter.js
- packages/agent-ui/src/components/segmentsFilter.test.js
- packages/agent-ui/src/containers/processSegmentsPage.test.js
- packages/agent-ui/src/utils/uuidUtils.js
- packages/agent-ui/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/274)
> agent-ui: automatically fetch segments on filter update

- packages/ember-mapexplorer/addon/components/evidences-component.js
- packages/ember-mapexplorer/addon/helpers/join.js
- packages/ember-mapexplorer/addon/templates/components/map-explorer.hbs
- packages/ember-mapexplorer/tests/dummy/app/controllers/application.js
- packages/ember-mapexplorer/tests/unit/helpers/join-test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/276)
> ember-mapexplorer: fix evidence and update example

- packages/agent-js/src/fossilizerHttpClient.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/282)
> agent-js: fix comment typo

- packages/agent-js/README.md
- packages/agent-sample/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/284)
> agent-sample: use clientFactory
