stratumn/agent

packages/agent-js/README.md, packages/agent-js/src/index.js, packages/agent-js/src/websocketServer.js
Creates a websocket for agent-client-js on ws://localhost:3000 when http server is started. storeHttpClient events are propagated to web socket.
Use `const server = Agent.listen(agent, storeHttpClient)` to start server and websocket.
TODO: Implementation on agent-client-js
=> Add websocket to agent-js (subscribed by agent-client-js)

packages/agent-client-js/package.json, packages/agent-client-js/src/makeQueryString.js, packages/agent-client-js/test/findSegments.js
https://github.com/stratumn/indigo-js/issues/17
use node library qs to encode query strings which is also used by express extended query parser to decode query strings. See: http://expressjs.com/en/api.html
=> agent-client-js: use qs for querystring encoding to handle arrays

packages/agent-js/package.json, packages/agent-js/src/makeQueryString.js, packages/agent-js/test/makeQueryString.js, packages/agent-js/test/storeHttpClient.js
`storeHttpClient` will now use brackets when making requests to the store
that contain arrays in the query string.
For example:
GET /segments?mapIds[]=id1&mapIds[]=id2&tags[]=t1&tags[]=t2
=> agent-js: use brackets for query arrays

.gitignore
since root level has its own dev deps, we should ignore node_modules/ folder
=> agent-ui: add node_modules to gitignore

packages/agent-ui/src/components/agentInfoPage.js, packages/agent-ui/src/components/app.js, packages/agent-ui/src/components/index.js, packages/agent-ui/src/components/processInfoPage.js, packages/agent-ui/src/routes.js, packages/agent-ui/src/setupTests.js, packages/agent-ui/src/store/dom.js, packages/agent-ui/src/test/components/agentInfoPage.test.js, packages/agent-ui/src/test/components/processInfoPage.test.js
Also in this PR:
* changed a bit the way we test components based on community best practices: I was previously kind of testing that redux worked well (using the store to dispatch props) whereas I can simplify this by testing only the components in isolation and trust that redux works
* moved the call to get agent info to the initialization (otherwise it wasn't executed when a user directly goes to a process url such as http://localhost:4000/myprocess)
Not in this PR but will come in a separate one:
* I'll add some tests for mapStateToProps
* I'll test the sub-components of the process info page (StoreSection, ActionsSection, FossilizersSection)
=> agent-ui: add the process info page

package.json, packages/agent-ui/src/components/agentInfoPage.js, packages/agent-ui/src/components/app.js, packages/agent-ui/src/components/processInfoPage.js, packages/agent-ui/src/reducers/index.js, packages/agent-ui/src/setupTests.js, packages/agent-ui/src/test/components/processInfoPage.test.js
some packages have a different name than the directory they are in and they were missed by the previous lint:ci script.
We could have renamed the directories/package but I think this solution is not too ugly. Let me know what you think.
=> ci: fix lint tests

packages/agent-js/src/create.js, packages/agent-js/src/fossilizerHttpClient.js, packages/agent-js/src/storeHttpClient.js, packages/agent-js/test/create.js, packages/agent-js/test/storeFossilizerClient.js, packages/agent-js/test/storeHttpClient.js
This is a first step to support dynamically adding new processes to a running agent.
The agent needs to expose the fossilizers and stores that it already knows. This way the new process that will be added can either directly use one of those or supply new { url, name } objects to use.
I'm really not sure this code is the best way to achieve this, don't hesitate to suggest something completely different or tell me if you don't like it :)
=> agent-js: track fossilizer and store clients created

.travis.yml, package.json
There are a few issues with using separate builds per package in the mono-repo:
- it looks like sometime the mapexplore-core build simply didn't start at all (Travis throttling us?)
- most of the time the builds were run sequentially, not in parallel, so the overall build time was much longer
- most of the build time is spent in the bootstrapping part anyway, so it's a bit of a waste to do that in each separate build
Most of these issues are probably because we're on the public (free) Travis.
=> build: use a single travis build for all packages

packages/agent-js/src/httpServer.js, packages/agent-js/test/httpServer.js
Adding a new API on the agent to allow dynamic upload of a new process (by script injection).
We most likely only want to allow this for test networks as an opt-in (it's way too dangerous otherwise) so I think I'll disable this API by default and allow enabling it (instead of having it enabled by default like what we have in this PR). What do you think?
Note: this is still lacking configuration of the store and fossilizer (hence the memorystore used and null fossilizer). This will come in another PR to keep this one small (since it raises a few issues, I'd like to focus on those before implementing store/fossilizer configuration which can also raise other issues).
=> agent-js: API to add a new process

packages/agent-js/src/fossilizerHttpClient.js, packages/agent-js/src/httpServer.js, packages/agent-js/src/storeHttpClient.js, packages/agent-js/test/create.js, packages/agent-js/test/httpServer.js, packages/agent-js/test/storeFossilizerClient.js, packages/agent-js/test/storeHttpClient.js
Adding store and fossilizer configuration options to the process upload API.
Refactored the process upload API as well (extracted several smaller functions).
I have one open question about the evidence callback url: I'm currently forcing the caller to specify a callback url for each fossilizer. This is maybe a bit drastic, if none is specified I could use agent.agentUrl or something like it as a default value, what do you think?
Overall I found that the evidence callback url could be configured via a few different variables so I'm a bit unclear about this, maybe it needs a bit of refactoring?
=> agent-js: process upload API accepts store and fossilizer configuration

packages/agent-js/src/create.js, packages/agent-js/src/httpServer.js, packages/agent-js/test/create.js, packages/agent-js/test/httpServer.js
When uploading a new process to a running agent, we want to be able to re-use existing plugins for this new process.
Agent now stores and exposes the plugins it has already instantiated, and uploaded processes specify the ids of the plugin instances they want to use.
=> agent-js: process upload: allow plugin configuration

packages/agent-ui/src/containers/processMapsPage.js, packages/agent-ui/src/containers/processMapsPage.test.js, packages/agent-ui/src/containers/processSegmentsPage.js, packages/agent-ui/src/containers/processSegmentsPage.test.js
this enables re fetching maps or segments when going from `/agent1/processA/segments` to `/agent2/processB/segments` (same for maps)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/98)
=> agent-ui: refetch maps and segments when props change

packages/agent-ui/src/containers/leftNavigation.js, packages/agent-ui/src/containers/root.js, packages/agent-ui/src/reducers/createMap.js
We had a few test warnings, mainly because of import problems: when using an index.js and import from it we're basically importing an object containing all the nested exports, and sometimes it means that some code executes that we don't want to execute in unit tests.
Using file imports in some places fixes these issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/105)
=> agent-ui: fix test warnings

.travis.yml
#96 
Looks like it works out of the box, no code changes needed.
We can start using async/await features now ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/103)
=> build: add node v8 in our build configuration

packages/agent-js/package.json, packages/agent-js/src/hashJson.js
Updated canonicaljson package to use github.com/stratumn/canonicaljson-js. This is a requirement to add linkHash validation in sdk.
Resolves #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/110)
=> agent-js: canonicaljson

packages/angular-mapexplorer/docs/home.html, packages/angular-mapexplorer/docs/src/Home.controller.js, packages/angular-mapexplorer/docs/styles/main.css, packages/angular-mapexplorer/docs/styles/map.css, packages/angular-mapexplorer/src/ChainTreeBuilder.service.js, packages/angular-mapexplorer/src/stMapExplorer.directive.js, packages/mapexplorer-core/src/ChainTreeBuilder.js
@such I had to change what we discussed about sending the map-explorer `options` to the `ChainTreeBuilder` constructor : it is still the case but since angular-mapexplorer can modify the options dynamically, it is now possible (again) to update them by calling `ChainTreeBuilder(map, options)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/111)
=> angular-mapexplorer: support segments merging

packages/agent-ui/src/actions/appendSegment.js, packages/agent-ui/src/actions/appendSegment.test.js, packages/agent-ui/src/components/appendSegmentButton.js, packages/agent-ui/src/components/appendSegmentButton.test.js, packages/agent-ui/src/containers/app.js, packages/agent-ui/src/containers/appendSegmentDialog.js, packages/agent-ui/src/containers/appendSegmentDialog.test.js, packages/agent-ui/src/containers/createMapDialog.test.js, packages/agent-ui/src/containers/index.js, packages/agent-ui/src/containers/topBar.js, packages/agent-ui/src/containers/topBar.test.js
Create a basic append segment dialog that can be opened and closed.
List available actions in a dropdown, and populates these actions from state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/120)
=> agent-ui: append segment dialog lists actions

packages/agent-js/src/plugins/agentVersion.js, packages/agent-js/test/plugins/agentVersion.js, packages/angular-mapexplorer/.gitignore
This adds a plugin to save the agent version in the segments `link.meta` object. 
I also noticed when bootstrapping this project that the `yarn.lock` file of the agent-ui was updated. That is included in a separate commit. Not sure if this PR is the appropriate place for that but we should probably update the lock file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/123)
=> Save agent version in segment

packages/agent-ui/src/actions/appendSegment.js, packages/agent-ui/src/actions/appendSegment.test.js
It doesn't make sense to expose the init action when appending to an existing segment.
Init should only be used when creating a new map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/128)
=> agent-ui: don't show the init action when appending a segment

packages/agent-client-js/src/objectAdaptor.js, packages/agent-js/src/create.js, packages/agent-js/src/httpServer.js, packages/agent-js/test/create.js, packages/agent-js/test/httpServer.js
Fix #127 
- The format being used by `agent.getAllProcesses()`is now consistent with the one already in use in `agent.getInfo()`
- Since we are actually querying the store and fossilizers when calling `getAllProcesses` (unlike before), an httpMockServer is now used for testing dynamic process addition. (this is why store/fossilizers urls are set to `http://localhost`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/134)
=> agent-js: /processes and /:process/remove resolve with public data

packages/agent-ui/.dockerignore, packages/agent-ui/Dockerfile, packages/agent-ui/package.json
Create a docker image with agent-ui running in it.
The image created looks good but at runtime there is an issue with radium.
I suspect it's because we haven't pushed recent versions of the other indigo JS packages to npm (map-explorer especially) and the docker image gets an outdated radium version incompatible with the latest react.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/138)
=> agent-ui: create docker image

packages/agent-ui/src/containers/topBar.js, packages/agent-ui/src/containers/topBar.test.js, packages/agent-ui/src/utils/shortHash.js, packages/agent-ui/src/utils/shortHash.test.js
display short segment hash in top bar instead of full hash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/143)
=> agent-ui: short segment hash

packages/agent-ui/src/containers/selectRefsDialog.js
In some cases, the agent can not be initialized in the store
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/163)
=> agent-ui: Fix selectRefsDialog for undef agent

packages/agent-ui/package.json, packages/agent-ui/src/actions/appendSegment.js, packages/agent-ui/src/actions/getAgent.js, packages/agent-ui/src/actions/getAgent.test.js, packages/agent-ui/src/constants/notificationTypes.js, packages/agent-ui/src/containers/app.js, packages/agent-ui/src/containers/index.js, packages/agent-ui/src/containers/webSocketsManager.js, packages/agent-ui/src/containers/webSocketsManager.test.js, packages/agent-ui/src/utils/notificationHelpers.js, packages/agent-ui/src/utils/notificationHelpers.test.js, packages/agent-ui/src/utils/webSocketHelpers.js, packages/agent-ui/src/utils/webSocketHelpers.test.js, packages/agent-ui/yarn.lock
We open a websocket for each agent in the state. This websocket can dispatch new notification on `didSave` message that will make the `mapexplorer` refresh if someone else added a new segment.
At the moment, 2 notifications are disptached when I add a new segment: 1 from the appendSegment action and 1 from the websocket message we receive on didSave event. It all happens in the same tick so it does not refresh twice but we should fix this IMO.
We could rely on the didSave notification only to refresh the mapexplorer but I don't think it is very reliable, as it can be delayed (if consensus takes long time for ex..). It would be better to have a way to uniquely identify notifications (hash instead of uuid?) and check if we've already seen it.
---
This change is [<img …
=> agent-ui: add websocket notifications

.prettierignore
Since package.json are already formatted by yarn, they should not be formatted by prettier. It can make actual changes harder to detect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/162)
=> *: ignore package.json with prettier

.travis.yml
yarn global librairies have been removed from the PATH in travis, it needs to be added manually.
another solution would be to add the codecov dependencies in `package.json`...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/176)
=> ci: fix path for global deps

.dockerignore, packages/agent-ui/Dockerfile.local, packages/agent-ui/yarn.lock, packages/cs-validator/yarn.lock
Create a docker image that will use the monorepo and latest version for stratumn dependencies.
This is a first step for a better solution to test the full Indigo stack locally from latest sources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/179)
=> agent-ui: docker local image

packages/agent-ui/src/constants/status.js, packages/agent-ui/src/containers/agentsPage.js, packages/agent-ui/src/containers/agentsPage.test.js, packages/agent-ui/src/reducers/agents.js, packages/agent-ui/src/reducers/agents.test.js
On REHYDRATE (redux-persist action) we set all the agents that have been persisted to STALE. I have not found a good way to always persist the agents as STALE, so instead I do this on rehydrate.
The AgentsManager is in charge of fetching the info for all stale agents, on mount.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/182)
=> agent-ui: fetches stale agents on startup

packages/agent-client-js/src/request.js, packages/agent-js/src/error.js, packages/agent-js/src/httpServer.js
I discussed this with @stephan83 and there is no specific reason to format errors as links anymore.
The agent-client-ruby needs to be updated as well (I'm on it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/178)
=> agent, agent-client: stop rendering errors as links

packages/agent-ui/src/reducers/agents.js, packages/agent-ui/src/reducers/agents.test.js
When no agent has ever been added to the UI, the REYDRATE action payload
is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/186)
=> agent-ui: handle empty redux-persist payload

packages/agent-ui/src/containers/selectRefsDialog.js
They used to be marked as required even though the Dialog is included in
the page when none is available.
Closes #173 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/187)
=> agent-ui: mark agent and process as optional in SelectRefsDialog

packages/agent-client-js/package.json, packages/agent-js/package.json, packages/agent-sample/package.json, packages/agent-ui/package.json, packages/angular-mapexplorer/package.json, packages/angular2-mapexplorer/package.json, packages/cs-validator/package.json, packages/mapexplorer-core/package.json, packages/react-mapexplorer/package.json, packages/tmpop-explorer/package.json
Scoped packages cannot be private if we want lerna to publish them.
Scoped packages need the publishConfig in each package.json according to lerna's documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/190)
=> release: update package.json for publish

packages/agent-ui/Dockerfile
Uncompressed to size goes from ~900MB to ~500MB
No additional apk package seems to be necesssary. Only the `fsevents` dependency fails to be installed but I don't think it's a big deal inside that Docker image.
If we wanted to install it we'd have to add:
`RUN apk add --no-cache git make gcc g++`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/198)
=> agent-ui: use alpine to reduce docker image size

packages/agent-client-js/package.json, packages/agent-js/package.json, packages/agent-sample/package.json, packages/agent-ui/package.json, packages/angular-mapexplorer/package.json, packages/angular2-mapexplorer/package.json, packages/cs-validator/package.json, packages/mapexplorer-core/package.json, packages/react-mapexplorer/package.json, packages/tmpop-explorer/app/package.json, packages/tmpop-explorer/package.json, publish-docker-tagged-images.sh
Pushed 0.2.0-3 release candidate.
Found that there is a Github limitation which prevents lerna's publish from triggering docker builds, so I added a script that we need to run after lerna publish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/200)
=> release: 0.2.0-3

packages/agent-js/Dockerfile.development, packages/agent-js/Dockerfile.development.alpine
To optimize the caching performed by Docker, we first copy the
package.json to the Docker image and install the dependencies. We then
use a mounted volume for all the src files and the actual package.json
from which we run the npm commands. Since this package.json is not at
the same level where the dependencies were installed, it isn't aware of
the available binaries. We use to install these dependencies globally to
work around this issue, but it is slower at build time and adds
duplication.
We chose instead to update the PATH so that is takes into account the
"local" dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/204)
=> agent-js: update PATH with npm binaries in Docker

packages/react-mapexplorer/src/mapExplorerCss.js
I don't know whether we should merge it before the release (it would make the tutorials screenshot out of date even though that's not a huge deal...)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/206)
=> react-mapexplorer: use updated style

packages/agent-ui/src/components/actionArgumentFields.js
Since the key was the args name, React didn't re-render previous form content.
So there was a mismatch between the state and what the UI showed.
#209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/212)
=> agent-ui: disable ui caching for form arguments

packages/agent-ui/src/containers/agentInfoPage.js, packages/agent-ui/src/containers/leftNavigation.js
React's `Link` component seems to be used by internal links only, `a` is now used instead.
Old links have been updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/215)
=> agent-ui: fix external links wrong url

packages/agent-ui/src/containers/agentsPage.js, packages/agent-ui/src/containers/agentsPage.test.js, packages/agent-ui/src/containers/leftNavigation.js, packages/agent-ui/src/containers/webSocketsManager.js, packages/agent-ui/src/containers/webSocketsManager.test.js
The main issue was that only the agents page (/) handled loading the agents.
It should be the responsibility of the web sockets manager : 
* When the app mounts, all agents have been loaded from the persisted state and are STALE
* So we should fetch each one of them, which will open a web socket as well
* At the end of the app's life, we should close those web sockets
Resolves #214 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/216)
=> agent-ui: properly handle refresh on all routes

packages/agent-client-js/src/httpAdaptor.js
At the moment, if `agentUrl=http://something/agent`, then doing a `findSegments` ends up fetching: `http://something/process/segments` instead of `http://something/agent/process/segments`. This is how `url.resolve` works.
removing first slash solves this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/indigo-js/234)
=> client-js: remove first slash

packages/agent-ui/package.json, packages/angular-mapexplorer/docs/home.html, packages/angular2-mapexplorer/docs_src/app/app.component.html, packages/mapexplorer-core/assets/stylesheets/map.scss, packages/mapexplorer-core/assets/stylesheets/variables.scss, packages/mapexplorer-core/package.json, packages/mapexplorer-core/src/ChainTree.js, packages/mapexplorer-core/src/ChainTreeBuilder.js, packages/mapexplorer-core/src/treeUtils.js, packages/react-mapexplorer/rollup.config.js, packages/react-mapexplorer/src/MapExplorer.js, packages/react-mapexplorer/src/mapExplorerCss.js
and various improvements:
- deselect on click outside a segment
- factorize svg markers into mapexplorer-core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/255)
=> mapexplorer-*: reverse reference arrow

packages/agent-ui/yarn.lock, packages/angular-mapexplorer/src/stTmpopEvidence.directive.js, packages/angular-mapexplorer/test/fixtures/chainscript.json, packages/angular-mapexplorer/views/tmpopevidence.html, packages/angular2-mapexplorer/src/st-tmpop-evidence/st-tmpop-evidence.component.html, packages/angular2-mapexplorer/src/st-tmpop-evidence/st-tmpop-evidence.component.ts, packages/react-mapexplorer/src/BitcoinEvidence.js, packages/react-mapexplorer/src/DummyEvidence.js, packages/react-mapexplorer/src/TMPopEvidence.js, packages/react-mapexplorer/src/TMPopHeader.js
Adding more data in TM evidence. The most useful one is probably the validators/expected validators section that can help quickly see that a validator is missing.
If we want the evidence to be easily understood by anyone, I think we need to do quite a bunch of design work to figure out how to visualize it. It will probably involve an interactive component to let the user dive into evidence parts, so it's quite a bit of work that requires better design skills than mine :)
That's also something that wouldn't be specific to us but would work for every project that uses Tendermint, so it might be worth doing that in a completely separate repo?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> map-explorer: more data in TM evidence

packages/agent-client-js/package.json, packages/agent-client-js/rollup.browser.config.js, packages/agent-client-js/rollup.browser.min.config.js, packages/agent-client-js/rollup.npm.config.js, packages/agent-client-js/src/encoding.js, packages/agent-client-js/src/sign.js, packages/agent-client-js/src/withKey.js, packages/agent-client-js/test/createMap.js, packages/agent-client-js/test/encoding.js, packages/agent-client-js/test/segmentify.js, packages/agent-client-js/test/sign.js, packages/agent-client-js/test/withKey.js, packages/agent-client-js/yarn.lock, packages/angular2-mapexplorer/yarn.lock, packages/cs-validator/package.json, packages/ember-mapexplorer/yarn.lock, packages/mapexplorer-core/package.json
The old key format (json with `secret` and `type` attributes) was replaced by the PEM format. This allows us to increase the compatibility with existing PKI solutions by adopting the standard behavior for key and signature encoding.
Before being formatted to PEM, keys/signatures are serialized using the DER ASN.1 notation (the same way as the go standard library).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/260)
=> agent-client-js: keys use PEM format

packages/agent-client-js/package.json, packages/agent-js/package.json, packages/agent-sample/package.json, packages/agent-ui/package.json, packages/angular-mapexplorer/package.json, packages/angular2-mapexplorer/package.json, packages/cs-validator/package.json, packages/ember-mapexplorer/package.json, packages/mapexplorer-core/package.json, packages/react-mapexplorer/package.json, packages/tmpop-explorer/package.json, packages/utils/package.json
Since we renamed indigoframework to indigocore, docker images fail to build (`indigocore/0.2.0` is not published on npm). 
After discussing it with @t-bast, we don't think it's a big deal to bump the version on master because the rc1 is already published and we're getting closer to the release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/268)
=> *: bump version to 0.3.0-rc1

packages/agent-js/README.md, packages/agent-js/src/clientFactory.js, packages/agent-js/src/create.js, packages/agent-js/src/fossilizerHttpClient.js, packages/agent-js/src/index.js, packages/agent-js/src/storeHttpClient.js, packages/agent-js/test/clientFactory.js, packages/agent-js/test/create.js, packages/agent-js/test/fossilizerHttpClient.js, packages/agent-js/test/storeHttpClient.js
The way we used to cache the clients created was not compatible with
having mutliple client implementation. For instance, the agent object
should not depend directly on a client implementation as it used to be
the case. This forces the user of the Agent to use a factory to
instantiate its clients though (as seen in the README).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/js-indigocore/283)
=> agent: introduce a client factory for client caching

README.md
The agent model doesn't suit the evolved chainscript (refs, signatures, etc).
We will provide shared helper client-side packages in stratumn/js-core to interact with stores, fossilizers and visualize chainscript.
The tutorial will be replaced by sample applications.
=> readme: add deprecate notice
